// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// constants.js
export const SAVE_RSV_STATUS_TYPES = 'SAVE_RSV_STATUS_TYPES'
export const SAVE_GENDER_TYPES = 'SAVE_GENDER_TYPES'
export const SAVE_RSV_SOURCE_TYPES = 'SAVE_RSV_SOURCE_TYPES'
export const SAVE_MENU_MASUI_TYPES = 'SAVE_MENU_MASUI_TYPES'
export const SAVE_MENU_BLEEDING_TYPES = 'SAVE_MENU_BLEEDING_TYPES'
export const SAVE_MENU_HOSPITACL_NEED_TYPES = 'SAVE_MENU_HOSPITACL_NEED_TYPES'
export const SAVE_MENU_HOSPITAL_VISIT_TYPES = 'SAVE_MENU_HOSPITAL_VISIT_TYPES'
export const SAVE_MENU_MAKEUP_TYPES = 'SAVE_MENU_MAKEUP_TYPES'
export const SAVE_MENU_MASSAGE_TYPES = 'SAVE_MENU_MASSAGE_TYPES'
export const SAVE_MENU_PAIN_TYPES = 'SAVE_MENU_PAIN_TYPES'
export const SAVE_MENU_SHOWER_TYPES = 'SAVE_MENU_SHOWER_TYPES'
export const SAVE_MENU_SPORT_IMPOSSIBLE_TYPES = 'SAVE_MENU_SPORT_IMPOSSIBLE_TYPES'
export const SAVE_MENU_BASSHI_TYPES = 'SAVE_MENU_BASSHI_TYPES'
export const SAVE_MENU_HARE_TYPES = 'SAVE_MENU_HARE_TYPES'
export const SAVE_MENU_TREAT_TIME_TYPES = 'SAVE_MENU_TREAT_TIME_TYPES'

// data.js
export const SAVE_STUFFS = 'SAVE_STUFFS'
export const ADD_STUFF = 'ADD_STUFF'
export const SAVE_RSV_CONTENTS = 'SAVE_RSV_CONTENTS'
export const SAVE_MENUS = 'SAVE_MENUS'
export const ADD_MENU = 'ADD_MENU'
export const SAVE_JOBS = 'SAVE_JOBS'
export const SAVE_SPECIALITIES = 'SAVE_SPECIALITIES'
export const SAVE_CATEGORIES = 'SAVE_CATEGORIES'
export const SAVE_TREATCATEGORIES = 'SAVE_TREATCATEGORIES'
export const SAVE_PREFS = 'SAVE_PREFS'

// state.js
export const SET_IS_ENUM_LOADED = 'SET_IS_ENUM_LOADED'
export const SET_IS_MASTER_LOADED = 'SET_IS_MASTER_LOADED'
export const SET_IS_LOADING = 'SET_IS_LOADING'
export const REMOVE_IS_LOADING = 'REMOVE_IS_LOADING'
